POST http://localhost:3001/api/blogs/
Content-Type: application/json

{
    "title": "Movie reviews 2",
    "author": "BC",
    "url": "https://www.youtube.com",
    "likes": 50,
    "userId": "616dbe8144a26fc68ae3d55b"
}